spring:
  application.name: test-task-spring-db-postgres-project
  profiles.active: local
  jackson:
    date-format: "dd-MM-yyyy"
    serialization:
      write_dates_as_timestamps: false

  datasource:
    url: "jdbc:postgresql://localhost:5432/testTaskFilmDirector"
    username: "postgres"
    password: "123456789"
    driver-class-name: org.postgresql.Driver

---
spring:
  config:
    activate:
      on-profile: local

server:
  port: 8082
  servlet.context-path: /hollywood